### ISSUE TITLE
猫猫帮助不生效

### ISSUE THREAD

**Issue by Kimaru-bili** [bridgeL/ayaka_games#1]
猫猫帮助+游戏名后提示没有找到对应猫猫
![Screenshot_2023-01-14-14-40-57-984_com tencent ti](https://user-images.githubusercontent.com/40233772/212459605-4f1c72b6-5ffe-41b8-b45e-6981b83e42ff.jpg)

**Comment by bridgeL** [comment]
用的什么bot框架？是什么版本的ayaka（启动时日志会说明）？还有配置文件截图一下我看看

**Comment by Kimaru-bili** [comment]
框架是：onebot V11 
![image](https://user-images.githubusercontent.com/40233772/212468190-dbe779b5-d933-458e-8909-1ceacde634f9.png)
![image](https://user-images.githubusercontent.com/40233772/212468372-f8efaeb1-0767-460d-ba89-912a1a3965c4.png)

**Comment by bridgeL** [comment]
哦，原来如此，因为你的配置项里，使用的是`.`作为分割符，所以，你发送猫猫帮助.背包应该可以用了

或者你修改command_sep为[" "]（一个空格）也可以

**Comment by Kimaru-bili** [comment]
emmm 之前没加分隔符的时候也不好使来着 我是尝试过不好使才加上的

**Comment by Kimaru-bili** [comment]
抱歉抱歉 好了 可能之前我是没加整个一行配置命令分隔符的锅 哈哈

**Comment by bridgeL** [comment]
XD

**Comment by Kimaru-bili** [comment]
感谢解惑(✪ω✪)
