### ISSUE TITLE
没有成功安装依赖

### ISSUE THREAD

**Issue by yuyue31** [bridgeL/ayaka_games#2]
大佬您好，请问是需要python3.10吗

**Comment by bridgeL** [comment]
是的，需要3.10，我稍后会更新到说明文档里

**Comment by yuyue31** [comment]
大佬再打扰一下，ERROR: unsupported operand type(s) for |: 'type' and 'type'和TypeError: 'type' object is not subscriptable是我这的问题吗

**Comment by bridgeL** [comment]
可以说明一下以下内容吗？
- 你用的机器人框架是什么
- 报错截图（至少保证最后几行的报错被截到）
- 你的配置文件截图

**Comment by yuyue31** [comment]
已经解决，是我的解释器没有更换成3.10，安装之后一直跳动
![RHZCDT 30$A}8 U %5_5}T3](https://user-images.githubusercontent.com/106214532/212523221-ccfca952-0fc5-4b8d-ba7d-3e3344c65c67.png)
然后我发的指令好像也没有触发，大佬求解答

**Comment by bridgeL** [comment]
我猜测应该是配置问题，信息太少我无法确定，你可以试试设置命令开头和分隔符为空字符串、空格

```
command_start=[""]
command_sep=[" "]
```

另外，是安装以后一直高频打印这两行日志的意思吗？感觉是个很严重的bug


可以说明一下以下内容吗？
- 你用的机器人框架是什么
- 报错截图（至少保证最后几行的报错被截到）
- 你的配置文件截图

**Comment by yuyue31** [comment]
我用的是hoshino框架，然后是py3.10启动的
![))~5`7X{TBL`95AACJ}2B04](https://user-images.githubusercontent.com/106214532/212525212-2d94fa73-8ae7-45f9-8821-a5189d66c2e6.png)
当我启动插件时显示这些
![ZE@B@I)$F1XNOVGVLH Z(98](https://user-images.githubusercontent.com/106214532/212525237-a035cb96-abf0-4909-82de-5bb5aa8f6d79.png)
![` R{{ _92MU{6(9I L8Y@RG](https://user-images.githubusercontent.com/106214532/212525247-6a05b82c-2c31-4f11-ab57-918045e162b1.png)
然后就一直在后台刷屏这两种信息
![$7`9C(5Q1Q}1O6@W(6R1QFP](https://user-images.githubusercontent.com/106214532/212525380-42c05c77-b044-426d-81cb-3493c861555b.png)
![WF1E2K5@}SCB(6`936$1$SE](https://user-images.githubusercontent.com/106214532/212525391-326cf881-874c-4539-83b3-71bf61141aa8.png)

**Comment by yuyue31** [comment]
我把command_start=[""]设置为空时就可以触发了，感谢大佬

**Comment by bridgeL** [comment]
哦，居然会这样，我一开始也有点担心写的有歧义，果然出事了

你看到的一大串1、2、3、4这些也是不正常的，因为你把整个ayaka_games都拖进去了，这是错误的，你应该只用ayaka_games/ayaka_games这个文件夹

我一会更新一下文档

**Comment by bridgeL** [comment]
具体来说是这样才对
![image](https://user-images.githubusercontent.com/47290820/212525875-c72c83ae-baa1-4085-8f83-7c4a11711895.png)
